version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PASSWORD=justas
      - DATABASE_NAME=postgres
      - DATABASE_USERNAME=postgres
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=justas
      - POSTGRES_DB=postgres

    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
